### ISSUE TITLE
buffer.js closures node-process preventing top-level node_modules overrides

### ISSUE THREAD

**Issue by twolfson** [browserify/insert-module-globals#6]
I am working off of a fork of [node-process](https://github.com/shtylman/node-process) and am using it as a top level `node_module` to override all other `require`s of it.

Unfortunately, `buffer.js` is generated pre-publish which means I need to fork + override this module as well to make things working. This is not a problem but it is more work/frustration.

I am wondering why you have a `pre-publish` step if this is a browserify module. Can't `buffer-browserify` be directly required?

**Comment by goto-bus-stop** [comment]
It looks like this was changed a long time ago. please open a new issue if it is still relevant. Thanks!
