### ISSUE TITLE
Upgrading combine-source-map for Windows issue

### ISSUE THREAD

**Issue by brettz9** [browserify/insert-module-globals#68]
The `combine-source-map` dependency has just been upgraded to a new minor version, 0.8.0 addressing a [Windows issue](https://github.com/thlorenz/combine-source-map/pull/24). Could you update `package.json` to make use of it? (I can add a PR, but I figure it would be nice to be accompanied by a version bump on your part anyways.)

**Comment by goto-bus-stop** [comment]
:package: 7.0.5
